global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey-chirkov'
