version: '3.3'
services:
  post_db:
    image: mongo:${version_mongodb}
    volumes:
      - post_db:/data/db
    networks:
      - back_net 
  ui:
    image: ${USER_NAME}/ui:${version}
    ports:
      - ${ui_port}
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${version}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USER_NAME}/comment:${version}
    networks:
      - back_net
      - front_net

volumes:
  post_db:
networks:
  back_net:
  front_net:

