version: '3'
services:
 
  zipkin:
    image: openzipkin/zipkin
    networks:
      - back_net
      - front_net
    ports:
      - "9411:9411"
      
  fluentd:
    image: ${USER_NAME}/fluentd
    networks:
      - back_net
      - front_net
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.3.2
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
    networks:
      - back_net
      - front_net
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.3.2
    ports:
      - "5601:5601"
    networks:
      - back_net
      - front_net

networks:
  back_net:
  front_net:
