version: '3.3'
services:
  post_db:
    image: mongo:${version_mongodb}
    volumes:
      - post_db:/data/db
    networks:
      - back_net 
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${version_ui}
    ports:
      - ${ui_port}
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${version_post}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${version_comment}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
  front_net:

